// Guided installer. Run with: npm run setup
//
// Walks a non-technical user from a fresh clone to a working dev environment
// without making them read the README. Specifically:
//   1. Detects what's already configured in .env.local
//   2. If missing, prompts for the three Supabase values and writes .env.local
//   3. Applies the database migrations against their Supabase project
//   4. Runs the seed (which prints the API tokens)
//   5. Optionally registers Claude Code MCP entries for each station
//
// Designed to be safely re-runnable: if everything's already set up, it
// detects that and exits with a no-op.

import fs from "node:fs";
import path from "node:path";
import readline from "node:readline";
import { spawn, spawnSync, execSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..");
const ENV_LOCAL = path.join(ROOT, ".env.local");
const MIGRATION = path.join(
  ROOT,
  "supabase",
  "migrations",
  "20260101000000_init.sql",
);
const TOKENS_MIGRATION = path.join(
  ROOT,
  "supabase",
  "migrations",
  "20260102000000_api_tokens.sql",
);

// ---------- Pretty output ----------
const C = {
  dim: (s: string) => `\x1b[2m${s}\x1b[0m`,
  bold: (s: string) => `\x1b[1m${s}\x1b[0m`,
  green: (s: string) => `\x1b[32m${s}\x1b[0m`,
  red: (s: string) => `\x1b[31m${s}\x1b[0m`,
  cyan: (s: string) => `\x1b[36m${s}\x1b[0m`,
  yellow: (s: string) => `\x1b[33m${s}\x1b[0m`,
};

function header(text: string) {
  console.log("\n" + C.bold(C.cyan("▍ " + text)));
}
function ok(text: string) {
  console.log("  " + C.green("✓") + " " + text);
}
function warn(text: string) {
  console.log("  " + C.yellow("⚠") + " " + text);
}
function fail(text: string): never {
  console.log("  " + C.red("✗") + " " + text);
  process.exit(1);
}

// ---------- Prompt helper ----------
function prompt(question: string, opts: { mask?: boolean } = {}): Promise<string> {
  return new Promise((resolve) => {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });
    if (opts.mask) {
      // Best-effort masked input. Not bulletproof but adequate for terminals.
      const stdin = process.stdin as NodeJS.ReadStream & { setRawMode?: (m: boolean) => void };
      const orig = stdin.isRaw;
      stdin.setRawMode?.(true);
    }
    rl.question(C.bold(question), (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

async function confirm(question: string, defaultYes = true): Promise<boolean> {
  const suffix = defaultYes ? " [Y/n]: " : " [y/N]: ";
  const ans = (await prompt(question + suffix)).toLowerCase();
  if (!ans) return defaultYes;
  return ans === "y" || ans === "yes";
}

// ---------- Env file ----------
interface EnvShape {
  NEXT_PUBLIC_SUPABASE_URL?: string;
  NEXT_PUBLIC_SUPABASE_ANON_KEY?: string;
  SUPABASE_SERVICE_ROLE_KEY?: string;
  OPENAI_API_KEY?: string;
  DEMO_USER_EMAIL?: string;
  DEMO_USER_PASSWORD?: string;
}

function readEnv(): EnvShape {
  if (!fs.existsSync(ENV_LOCAL)) return {};
  const text = fs.readFileSync(ENV_LOCAL, "utf-8");
  const out: EnvShape = {};
  for (const line of text.split("\n")) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (m) (out as any)[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
  return out;
}

function writeEnv(env: EnvShape) {
  const lines: string[] = [
    "# Generated by `npm run setup`. Edit by hand if you need to.",
    `NEXT_PUBLIC_SUPABASE_URL=${env.NEXT_PUBLIC_SUPABASE_URL ?? ""}`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY=${env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? ""}`,
    `SUPABASE_SERVICE_ROLE_KEY=${env.SUPABASE_SERVICE_ROLE_KEY ?? ""}`,
    `OPENAI_API_KEY=${env.OPENAI_API_KEY ?? ""}`,
    `DEMO_USER_EMAIL=${env.DEMO_USER_EMAIL ?? "demo@agent-republics.local"}`,
    `DEMO_USER_PASSWORD=${env.DEMO_USER_PASSWORD ?? "republic-demo-2026"}`,
    "",
  ];
  fs.writeFileSync(ENV_LOCAL, lines.join("\n"), { mode: 0o600 });
}

// ---------- Step: collect env ----------
async function collectEnv(): Promise<EnvShape> {
  header("Step 1: Supabase configuration");
  const env = readEnv();

  const haveAll =
    env.NEXT_PUBLIC_SUPABASE_URL &&
    env.NEXT_PUBLIC_SUPABASE_ANON_KEY &&
    env.SUPABASE_SERVICE_ROLE_KEY;

  if (haveAll) {
    ok(`.env.local already has Supabase keys for ${env.NEXT_PUBLIC_SUPABASE_URL}`);
    return env;
  }

  console.log(`
  ${C.dim("You need a free Supabase project. If you don't have one yet:")}
   1. Open https://supabase.com and create a project (~2 minutes)
   2. In the project dashboard, go to: Project Settings → API
   3. Copy the three values below.
`);

  if (!env.NEXT_PUBLIC_SUPABASE_URL) {
    env.NEXT_PUBLIC_SUPABASE_URL = await prompt(
      "  Project URL (https://xxxx.supabase.co): ",
    );
  }
  if (!env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
    env.NEXT_PUBLIC_SUPABASE_ANON_KEY = await prompt("  anon public key: ");
  }
  if (!env.SUPABASE_SERVICE_ROLE_KEY) {
    env.SUPABASE_SERVICE_ROLE_KEY = await prompt("  service_role key: ");
  }
  if (!env.DEMO_USER_EMAIL) env.DEMO_USER_EMAIL = "demo@agent-republics.local";
  if (!env.DEMO_USER_PASSWORD) env.DEMO_USER_PASSWORD = "republic-demo-2026";

  if (!env.NEXT_PUBLIC_SUPABASE_URL?.startsWith("https://")) {
    fail("That URL doesn't look right. It should start with https://");
  }

  writeEnv(env);
  ok(`Wrote ${path.relative(ROOT, ENV_LOCAL)}`);
  return env;
}

// ---------- Step: apply migrations via REST ----------
async function applyMigrations(env: EnvShape) {
  header("Step 2: Apply database migrations");

  if (!fs.existsSync(MIGRATION) || !fs.existsSync(TOKENS_MIGRATION)) {
    fail("Migration files not found. Did you clone the repo correctly?");
  }

  // Supabase doesn't expose arbitrary SQL execution over the REST API. Two
  // ways to run the migration: the Supabase CLI (preferred when present),
  // or asking the user to paste it themselves. We try the CLI first; if it
  // fails or isn't installed, we walk the user through the manual path.
  const cli = spawnSync("supabase", ["--version"], { stdio: "ignore" });
  if (cli.status === 0) {
    ok("Supabase CLI detected. Pushing migrations...");
    const result = spawnSync(
      "supabase",
      ["db", "push", "--password", env.DEMO_USER_PASSWORD ?? ""],
      { cwd: ROOT, stdio: "inherit" },
    );
    if (result.status !== 0) {
      warn(
        "supabase db push didn't complete. Falling back to manual SQL paste.",
      );
      await manualSqlInstructions();
    } else {
      ok("Migrations applied via CLI.");
    }
  } else {
    warn("Supabase CLI not installed.");
    await manualSqlInstructions();
  }
}

async function manualSqlInstructions() {
  const projectRef = readEnv()
    .NEXT_PUBLIC_SUPABASE_URL?.replace("https://", "")
    .replace(".supabase.co", "");
  const sqlEditor = projectRef
    ? `https://supabase.com/dashboard/project/${projectRef}/sql/new`
    : "https://supabase.com/dashboard → SQL Editor → New query";
  console.log(`
  ${C.bold("Manual SQL apply (one-time):")}
    1. Open: ${C.cyan(sqlEditor)}
    2. Copy the contents of:
       ${C.dim(path.relative(ROOT, MIGRATION))}
       into the editor and click Run.
    3. Then copy and run:
       ${C.dim(path.relative(ROOT, TOKENS_MIGRATION))}

  ${C.dim("(Re-running these is safe — they use CREATE TABLE IF NOT EXISTS.)")}`);
  await prompt(
    "  Press Enter once both migrations have been applied... ",
  );
  ok("Continuing.");
}

// ---------- Step: seed ----------
async function runSeed(): Promise<{ tokens: { station: string; plaintext: string }[] }> {
  header("Step 3: Seed demo data");
  ok("Running npm run db:seed...");

  return new Promise((resolve, reject) => {
    const proc = spawn("npm", ["run", "db:seed"], {
      cwd: ROOT,
      stdio: ["inherit", "pipe", "pipe"],
    });

    let stdout = "";
    proc.stdout.on("data", (d) => {
      const s = d.toString();
      stdout += s;
      process.stdout.write(s);
    });
    proc.stderr.on("data", (d) => process.stderr.write(d));
    proc.on("close", (code) => {
      if (code !== 0) {
        return reject(new Error(`Seed failed with code ${code}`));
      }
      // Parse tokens out of the output
      const lineRe = /^\s+([A-Za-z][^\s][^\s]*(?:\s[A-Za-z0-9]+)*)\s+(rs_[a-z0-9-]+_[A-Za-z0-9_-]+)\s*$/gm;
      const tokens: { station: string; plaintext: string }[] = [];
      let m: RegExpExecArray | null;
      while ((m = lineRe.exec(stdout))) {
        tokens.push({ station: m[1].trim(), plaintext: m[2] });
      }
      resolve({ tokens });
    });
  });
}

// ---------- Step: configure Claude Code MCP ----------
async function configureMcp(tokens: { station: string; plaintext: string }[]) {
  header("Step 4: Wire up Claude Code (optional)");

  const cli = spawnSync("claude", ["--version"], { stdio: "ignore" });
  if (cli.status !== 0) {
    warn(
      "Claude Code CLI (`claude`) not detected. Skipping MCP registration.",
    );
    console.log(
      `  Install Claude Code from https://docs.anthropic.com/en/docs/claude-code or follow the README's "Connecting an external agent" section to wire up the MCP yourself.`,
    );
    return;
  }

  const yes = await confirm(
    "  Register Agentic Republic MCP servers in Claude Code now? You can do this later if you prefer.",
    true,
  );
  if (!yes) {
    console.log(
      `  Skipped. To do this later, see the "Connecting an external agent" section in README.`,
    );
    return;
  }

  // Build MCP if dist/ is missing
  const mcpDist = path.join(ROOT, "mcp", "dist", "server.js");
  if (!fs.existsSync(mcpDist)) {
    ok("Building MCP server...");
    spawnSync("npm", ["install", "--no-audit", "--no-fund"], {
      cwd: path.join(ROOT, "mcp"),
      stdio: "inherit",
    });
    spawnSync("npm", ["run", "build"], {
      cwd: path.join(ROOT, "mcp"),
      stdio: "inherit",
    });
  }

  // Register one MCP entry per station
  for (const { station, plaintext } of tokens) {
    const slug = station
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");
    const name = `agentic-republic-${slug}`;
    spawnSync("claude", ["mcp", "remove", name, "--scope", "user"], {
      stdio: "ignore",
    });
    const add = spawnSync(
      "claude",
      [
        "mcp",
        "add",
        name,
        "--scope",
        "user",
        "-e",
        "AGENTIC_REPUBLIC_URL=http://localhost:3000",
        "-e",
        `AGENTIC_REPUBLIC_TOKEN=${plaintext}`,
        "--",
        "node",
        mcpDist,
      ],
      { stdio: "inherit" },
    );
    if (add.status === 0) {
      ok(`Registered ${name}`);
    } else {
      warn(
        `Could not auto-register ${name}. You can add it manually with:\n     claude mcp add ${name} --scope user -e AGENTIC_REPUBLIC_TOKEN=${plaintext} -- node "${mcpDist}"`,
      );
    }
  }
}

// ---------- main ----------
async function main() {
  console.log(C.bold(C.cyan("\n  Agentic Republic — guided setup")));
  console.log(C.dim("  This walks you through env, migrations, seed, and MCP."));

  const env = await collectEnv();
  await applyMigrations(env);
  const { tokens } = await runSeed();

  if (tokens.length === 0) {
    warn("No tokens were parsed from the seed output. Re-run npm run db:seed manually.");
  } else {
    await configureMcp(tokens);
  }

  header("All set");
  console.log(`
  ${C.green("Next steps:")}
    1. Start the dev server:   ${C.cyan("npm run dev")}
    2. Open:                   ${C.cyan("http://localhost:3000")}
    3. Sign in with the seeded credentials (see your .env.local).
    4. Try a Claude Code session — your station MCPs are registered.

  ${C.dim("To rotate tokens or reset data, re-run this command.")}
`);
}

main().catch((err) => {
  console.error(C.red("\n  Setup failed: ") + (err?.message ?? String(err)));
  console.error(
    C.dim("  Most issues are about Supabase keys. Re-run after fixing."),
  );
  process.exit(1);
});
